# Generated by Django 5.0.6 on 2024-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_good_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
